name: Deploy to CloudFlare Pages
on:
  push: 
    branches: [ "main" ]
    paths:
      - ".github/workflows/deploy.yml"
      - "document/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/deploy.yml"
      - "document/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Static Site
        run: |
          curl -L -O https://github.com/swagger-api/swagger-ui/archive/refs/heads/main.zip
          7z x master.zip
          cp -r swagger-ui-master/dist out
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|https://apidocs.shuttle.pub/api/v1.yaml|' out/swagger-initializer.js 
          mkdir -p out/api
          cp document/v1.yaml out/api

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "shuttlepub-document-webapi"
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
