name: Deploy to CloudFlare Pages
on:
  push: 
    branches: [ "main" ]
    paths:
      - ".github/workflows/deploy.yml"
      - "document/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/deploy.yml"
      - "document/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Static Site
        run: |
          mkdir out
          docker run --rm -v ${{ github.workspace }}:/local swaggerapi/swagger-codegen-cli-v3 generate -i /local/document/v1.yaml -l html2 -o /local/out
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "shuttlepub-document-webapi"
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
